{"url":"https://api.github.com/repos/willmcgugan/rich/issues/212","repository_url":"https://api.github.com/repos/willmcgugan/rich","labels_url":"https://api.github.com/repos/willmcgugan/rich/issues/212/labels{/name}","comments_url":"https://api.github.com/repos/willmcgugan/rich/issues/212/comments","events_url":"https://api.github.com/repos/willmcgugan/rich/issues/212/events","html_url":"https://github.com/willmcgugan/rich/issues/212","id":673848212,"node_id":"MDU6SXNzdWU2NzM4NDgyMTI=","number":212,"title":"Exception thrown when output is not configured as utf-8","user":{"login":"DonBraulio","id":12506292,"node_id":"MDQ6VXNlcjEyNTA2Mjky","avatar_url":"https://avatars0.githubusercontent.com/u/12506292?v=4","gravatar_id":"","url":"https://api.github.com/users/DonBraulio","html_url":"https://github.com/DonBraulio","followers_url":"https://api.github.com/users/DonBraulio/followers","following_url":"https://api.github.com/users/DonBraulio/following{/other_user}","gists_url":"https://api.github.com/users/DonBraulio/gists{/gist_id}","starred_url":"https://api.github.com/users/DonBraulio/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DonBraulio/subscriptions","organizations_url":"https://api.github.com/users/DonBraulio/orgs","repos_url":"https://api.github.com/users/DonBraulio/repos","events_url":"https://api.github.com/users/DonBraulio/events{/privacy}","received_events_url":"https://api.github.com/users/DonBraulio/received_events","type":"User","site_admin":false},"labels":[{"id":2200581776,"node_id":"MDU6TGFiZWwyMjAwNTgxNzc2","url":"https://api.github.com/repos/willmcgugan/rich/labels/Needs%20triage","name":"Needs triage","color":"bfdadc","default":false,"description":""}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":7,"created_at":"2020-08-05T21:07:29Z","updated_at":"2020-08-10T19:30:33Z","closed_at":"2020-08-10T19:30:33Z","author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\nRunning a program with a rich progressbar inside a docker container, I got the following exception:\r\n\r\n```\r\n  File \"/usr/local/lib/python3.6/dist-packages/rich/progress.py\", line 150, in track\r\n    sequence, total=total, description=description, update_period=update_period\r\n  File \"/usr/local/lib/python3.6/dist-packages/rich/progress.py\", line 667, in track\r\n    with self:\r\n  File \"/usr/local/lib/python3.6/dist-packages/rich/progress.py\", line 627, in __enter__\r\n    self.start()\r\n  File \"/usr/local/lib/python3.6/dist-packages/rich/progress.py\", line 596, in start\r\n    self.refresh()\r\n  File \"/usr/local/lib/python3.6/dist-packages/rich/progress.py\", line 812, in refresh\r\n    self.console.print(Control(\"\"))\r\n  File \"/usr/local/lib/python3.6/dist-packages/rich/console.py\", line 448, in __exit__\r\n    self._exit_buffer()\r\n  File \"/usr/local/lib/python3.6/dist-packages/rich/console.py\", line 426, in _exit_buffer\r\n    self._check_buffer()\r\n  File \"/usr/local/lib/python3.6/dist-packages/rich/console.py\", line 993, in _check_buffer\r\n    self.file.write(text)\r\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 16-55: ordinal not in range(128)\r\n```\r\n\r\nThe problem can be **easily solved in my case** by setting the encoding properly:\r\n```\r\nexport PYTHONIOENCODING=utf8\r\n```\r\n\r\nAfter that, the script runs perfectly fine with the beautiful rich progressbar.\r\n\r\nHowever, setting this env var in some environments might not be possible or have other undesired consequences. It would be great if there was some kind of failback mode, or a `WARNING` with a suggestion to set this var, instead of failing without further information.\r\n\r\n\r\n**To Reproduce**\r\nUse the README progressbar example, let's call this file `progress.py`:\r\n\r\n```python\r\nfrom rich.progress import track\r\nfor step in track(range(100)):\r\n    pass\r\n```\r\n\r\nRun it with `ascii` encoding vs. `utf8` and check the difference:\r\n```bash\r\nPYTHONIOENCODING=ascii python progress.py  # Exception thrown\r\nPYTHONIOENCODING=utf8 python progress.py  # Works\r\n```\r\n\r\n**Platform**\r\n* `rich==5.0.0`\r\n* Probably works on any python3 installation. Reproduced on Python 3.6.10 on OSX Catalina, and Python 3.6.9 on Ubuntu Linux native and the same version on Linux for tegra (ARM) docker image.","closed_by":{"login":"willmcgugan","id":554369,"node_id":"MDQ6VXNlcjU1NDM2OQ==","avatar_url":"https://avatars3.githubusercontent.com/u/554369?v=4","gravatar_id":"","url":"https://api.github.com/users/willmcgugan","html_url":"https://github.com/willmcgugan","followers_url":"https://api.github.com/users/willmcgugan/followers","following_url":"https://api.github.com/users/willmcgugan/following{/other_user}","gists_url":"https://api.github.com/users/willmcgugan/gists{/gist_id}","starred_url":"https://api.github.com/users/willmcgugan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/willmcgugan/subscriptions","organizations_url":"https://api.github.com/users/willmcgugan/orgs","repos_url":"https://api.github.com/users/willmcgugan/repos","events_url":"https://api.github.com/users/willmcgugan/events{/privacy}","received_events_url":"https://api.github.com/users/willmcgugan/received_events","type":"User","site_admin":false},"performed_via_github_app":null}