{"url":"https://api.github.com/repos/willmcgugan/rich/issues/395","repository_url":"https://api.github.com/repos/willmcgugan/rich","labels_url":"https://api.github.com/repos/willmcgugan/rich/issues/395/labels{/name}","comments_url":"https://api.github.com/repos/willmcgugan/rich/issues/395/comments","events_url":"https://api.github.com/repos/willmcgugan/rich/issues/395/events","html_url":"https://github.com/willmcgugan/rich/issues/395","id":725189263,"node_id":"MDU6SXNzdWU3MjUxODkyNjM=","number":395,"title":"[BUG] Failing mypy --strict due to implicit reexports","user":{"login":"paw-lu","id":30049606,"node_id":"MDQ6VXNlcjMwMDQ5NjA2","avatar_url":"https://avatars1.githubusercontent.com/u/30049606?v=4","gravatar_id":"","url":"https://api.github.com/users/paw-lu","html_url":"https://github.com/paw-lu","followers_url":"https://api.github.com/users/paw-lu/followers","following_url":"https://api.github.com/users/paw-lu/following{/other_user}","gists_url":"https://api.github.com/users/paw-lu/gists{/gist_id}","starred_url":"https://api.github.com/users/paw-lu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/paw-lu/subscriptions","organizations_url":"https://api.github.com/users/paw-lu/orgs","repos_url":"https://api.github.com/users/paw-lu/repos","events_url":"https://api.github.com/users/paw-lu/events{/privacy}","received_events_url":"https://api.github.com/users/paw-lu/received_events","type":"User","site_admin":false},"labels":[{"id":2200581776,"node_id":"MDU6TGFiZWwyMjAwNTgxNzc2","url":"https://api.github.com/repos/willmcgugan/rich/labels/Needs%20triage","name":"Needs triage","color":"bfdadc","default":false,"description":""}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2020-10-20T04:39:31Z","updated_at":"2020-10-21T16:18:28Z","closed_at":"2020-10-21T16:18:28Z","author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\n\r\nMypy raises a no attribute error when run with the `--strict` flag.\r\n\r\n**To Reproduce**\r\n\r\nGiven `file.py`\r\n\r\n```python\r\nfrom rich.console import Measurement\r\n\r\nMeasurement(10, 100)\r\n```\r\n\r\n```sh\r\n%mypy --strict file.py\r\nscratch/unpack.py:1: error: Module 'rich.console' has no attribute 'Measurement'\r\n```\r\n\r\n**Platform**\r\n\r\nPython: 3.89\r\nmacOS: 10.15.6\r\nRich: 9.0.1\r\n\r\n**Discussion**\r\n\r\nI saw this issue popping up in a few places.\r\n\r\n- [Mypy issue](https://github.com/python/mypy/issues/7030)\r\n- [Typer](https://github.com/tiangolo/typer/issues/112)\r\n- [Typer diff](https://github.com/tiangolo/typer/pull/147/files)\r\n\r\nThis seems to come up due to the new [`--no-implicit-reexport`](https://mypy.readthedocs.io/en/latest/command_line.html#cmdoption-mypy-no-implicit-reexport) flag.\r\n\r\nThe solution seems to be to go from this\r\n\r\n```python\r\nfrom foo import bar\r\n```\r\n\r\nto either of these\r\n\r\n```python\r\nfrom foo import bar as bar\r\n```\r\n\r\n```python\r\nfrom foo import bar\r\n__all__ = ['bar']\r\n```\r\n\r\nin your `__init__.py`","closed_by":{"login":"paw-lu","id":30049606,"node_id":"MDQ6VXNlcjMwMDQ5NjA2","avatar_url":"https://avatars1.githubusercontent.com/u/30049606?v=4","gravatar_id":"","url":"https://api.github.com/users/paw-lu","html_url":"https://github.com/paw-lu","followers_url":"https://api.github.com/users/paw-lu/followers","following_url":"https://api.github.com/users/paw-lu/following{/other_user}","gists_url":"https://api.github.com/users/paw-lu/gists{/gist_id}","starred_url":"https://api.github.com/users/paw-lu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/paw-lu/subscriptions","organizations_url":"https://api.github.com/users/paw-lu/orgs","repos_url":"https://api.github.com/users/paw-lu/repos","events_url":"https://api.github.com/users/paw-lu/events{/privacy}","received_events_url":"https://api.github.com/users/paw-lu/received_events","type":"User","site_admin":false},"performed_via_github_app":null}